import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
     <Head>
       <title>Shopsy</title>
       <meta name="description" content="generated by next app" />
     </Head>
     <h1>Next Shopsy</h1>
    </div>
  )
}
